// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ailawyer/backend.proto

package backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend_SignUPV1_FullMethodName                  = "/mrga.backend.Backend/SignUPV1"
	Backend_Login_FullMethodName                     = "/mrga.backend.Backend/Login"
	Backend_CheckLogin_FullMethodName                = "/mrga.backend.Backend/CheckLogin"
	Backend_BeginConversation_FullMethodName         = "/mrga.backend.Backend/BeginConversation"
	Backend_GetConversations_FullMethodName          = "/mrga.backend.Backend/GetConversations"
	Backend_GetConversation_FullMethodName           = "/mrga.backend.Backend/GetConversation"
	Backend_SendMessage_FullMethodName               = "/mrga.backend.Backend/SendMessage"
	Backend_GetDocumentCategories_FullMethodName     = "/mrga.backend.Backend/GetDocumentCategories"
	Backend_SendRedirectSuggest_FullMethodName       = "/mrga.backend.Backend/SendRedirectSuggest"
	Backend_GetHotThemes_FullMethodName              = "/mrga.backend.Backend/GetHotThemes"
	Backend_TestStreamFromServer_FullMethodName      = "/mrga.backend.Backend/TestStreamFromServer"
	Backend_TestStreamFromClient_FullMethodName      = "/mrga.backend.Backend/TestStreamFromClient"
	Backend_TestStreamClientAndServer_FullMethodName = "/mrga.backend.Backend/TestStreamClientAndServer"
)

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	SignUPV1(ctx context.Context, in *SignUPRequest, opts ...grpc.CallOption) (*SignUPResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CheckLogin(ctx context.Context, in *CheckLoginRequest, opts ...grpc.CallOption) (*CheckLoginResponse, error)
	BeginConversation(ctx context.Context, in *BeginConversationRequest, opts ...grpc.CallOption) (*BeginConversationResponse, error)
	GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GetDocumentCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	SendRedirectSuggest(ctx context.Context, in *SendRedirectSuggestRequest, opts ...grpc.CallOption) (*SendRedirectSuggestResponse, error)
	GetHotThemes(ctx context.Context, in *GetHotThemesRequest, opts ...grpc.CallOption) (*GetHotThemesResponse, error)
	TestStreamFromServer(ctx context.Context, in *TestMessageRequest, opts ...grpc.CallOption) (Backend_TestStreamFromServerClient, error)
	TestStreamFromClient(ctx context.Context, opts ...grpc.CallOption) (Backend_TestStreamFromClientClient, error)
	TestStreamClientAndServer(ctx context.Context, opts ...grpc.CallOption) (Backend_TestStreamClientAndServerClient, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) SignUPV1(ctx context.Context, in *SignUPRequest, opts ...grpc.CallOption) (*SignUPResponse, error) {
	out := new(SignUPResponse)
	err := c.cc.Invoke(ctx, Backend_SignUPV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Backend_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CheckLogin(ctx context.Context, in *CheckLoginRequest, opts ...grpc.CallOption) (*CheckLoginResponse, error) {
	out := new(CheckLoginResponse)
	err := c.cc.Invoke(ctx, Backend_CheckLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) BeginConversation(ctx context.Context, in *BeginConversationRequest, opts ...grpc.CallOption) (*BeginConversationResponse, error) {
	out := new(BeginConversationResponse)
	err := c.cc.Invoke(ctx, Backend_BeginConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error) {
	out := new(GetConversationsResponse)
	err := c.cc.Invoke(ctx, Backend_GetConversations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	out := new(GetConversationResponse)
	err := c.cc.Invoke(ctx, Backend_GetConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Backend_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetDocumentCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, Backend_GetDocumentCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SendRedirectSuggest(ctx context.Context, in *SendRedirectSuggestRequest, opts ...grpc.CallOption) (*SendRedirectSuggestResponse, error) {
	out := new(SendRedirectSuggestResponse)
	err := c.cc.Invoke(ctx, Backend_SendRedirectSuggest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetHotThemes(ctx context.Context, in *GetHotThemesRequest, opts ...grpc.CallOption) (*GetHotThemesResponse, error) {
	out := new(GetHotThemesResponse)
	err := c.cc.Invoke(ctx, Backend_GetHotThemes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) TestStreamFromServer(ctx context.Context, in *TestMessageRequest, opts ...grpc.CallOption) (Backend_TestStreamFromServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[0], Backend_TestStreamFromServer_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &backendTestStreamFromServerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Backend_TestStreamFromServerClient interface {
	Recv() (*TestMessageResponse, error)
	grpc.ClientStream
}

type backendTestStreamFromServerClient struct {
	grpc.ClientStream
}

func (x *backendTestStreamFromServerClient) Recv() (*TestMessageResponse, error) {
	m := new(TestMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backendClient) TestStreamFromClient(ctx context.Context, opts ...grpc.CallOption) (Backend_TestStreamFromClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[1], Backend_TestStreamFromClient_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &backendTestStreamFromClientClient{stream}
	return x, nil
}

type Backend_TestStreamFromClientClient interface {
	Send(*TestMessageRequest) error
	CloseAndRecv() (*TestMessageResponse, error)
	grpc.ClientStream
}

type backendTestStreamFromClientClient struct {
	grpc.ClientStream
}

func (x *backendTestStreamFromClientClient) Send(m *TestMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backendTestStreamFromClientClient) CloseAndRecv() (*TestMessageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TestMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backendClient) TestStreamClientAndServer(ctx context.Context, opts ...grpc.CallOption) (Backend_TestStreamClientAndServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[2], Backend_TestStreamClientAndServer_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &backendTestStreamClientAndServerClient{stream}
	return x, nil
}

type Backend_TestStreamClientAndServerClient interface {
	Send(*TestMessageRequest) error
	Recv() (*TestMessageResponse, error)
	grpc.ClientStream
}

type backendTestStreamClientAndServerClient struct {
	grpc.ClientStream
}

func (x *backendTestStreamClientAndServerClient) Send(m *TestMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backendTestStreamClientAndServerClient) Recv() (*TestMessageResponse, error) {
	m := new(TestMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BackendServer is the server API for Backend service.
// All implementations must embed UnimplementedBackendServer
// for forward compatibility
type BackendServer interface {
	SignUPV1(context.Context, *SignUPRequest) (*SignUPResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CheckLogin(context.Context, *CheckLoginRequest) (*CheckLoginResponse, error)
	BeginConversation(context.Context, *BeginConversationRequest) (*BeginConversationResponse, error)
	GetConversations(context.Context, *GetConversationsRequest) (*GetConversationsResponse, error)
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GetDocumentCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	SendRedirectSuggest(context.Context, *SendRedirectSuggestRequest) (*SendRedirectSuggestResponse, error)
	GetHotThemes(context.Context, *GetHotThemesRequest) (*GetHotThemesResponse, error)
	TestStreamFromServer(*TestMessageRequest, Backend_TestStreamFromServerServer) error
	TestStreamFromClient(Backend_TestStreamFromClientServer) error
	TestStreamClientAndServer(Backend_TestStreamClientAndServerServer) error
	mustEmbedUnimplementedBackendServer()
}

// UnimplementedBackendServer must be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (UnimplementedBackendServer) SignUPV1(context.Context, *SignUPRequest) (*SignUPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUPV1 not implemented")
}
func (UnimplementedBackendServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBackendServer) CheckLogin(context.Context, *CheckLoginRequest) (*CheckLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLogin not implemented")
}
func (UnimplementedBackendServer) BeginConversation(context.Context, *BeginConversationRequest) (*BeginConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginConversation not implemented")
}
func (UnimplementedBackendServer) GetConversations(context.Context, *GetConversationsRequest) (*GetConversationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversations not implemented")
}
func (UnimplementedBackendServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedBackendServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedBackendServer) GetDocumentCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentCategories not implemented")
}
func (UnimplementedBackendServer) SendRedirectSuggest(context.Context, *SendRedirectSuggestRequest) (*SendRedirectSuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRedirectSuggest not implemented")
}
func (UnimplementedBackendServer) GetHotThemes(context.Context, *GetHotThemesRequest) (*GetHotThemesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotThemes not implemented")
}
func (UnimplementedBackendServer) TestStreamFromServer(*TestMessageRequest, Backend_TestStreamFromServerServer) error {
	return status.Errorf(codes.Unimplemented, "method TestStreamFromServer not implemented")
}
func (UnimplementedBackendServer) TestStreamFromClient(Backend_TestStreamFromClientServer) error {
	return status.Errorf(codes.Unimplemented, "method TestStreamFromClient not implemented")
}
func (UnimplementedBackendServer) TestStreamClientAndServer(Backend_TestStreamClientAndServerServer) error {
	return status.Errorf(codes.Unimplemented, "method TestStreamClientAndServer not implemented")
}
func (UnimplementedBackendServer) mustEmbedUnimplementedBackendServer() {}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_SignUPV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SignUPV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SignUPV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SignUPV1(ctx, req.(*SignUPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CheckLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CheckLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_CheckLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CheckLogin(ctx, req.(*CheckLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_BeginConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).BeginConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_BeginConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).BeginConversation(ctx, req.(*BeginConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetConversations(ctx, req.(*GetConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetDocumentCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetDocumentCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetDocumentCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetDocumentCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SendRedirectSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRedirectSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SendRedirectSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SendRedirectSuggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SendRedirectSuggest(ctx, req.(*SendRedirectSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetHotThemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotThemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetHotThemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetHotThemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetHotThemes(ctx, req.(*GetHotThemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_TestStreamFromServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).TestStreamFromServer(m, &backendTestStreamFromServerServer{stream})
}

type Backend_TestStreamFromServerServer interface {
	Send(*TestMessageResponse) error
	grpc.ServerStream
}

type backendTestStreamFromServerServer struct {
	grpc.ServerStream
}

func (x *backendTestStreamFromServerServer) Send(m *TestMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Backend_TestStreamFromClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendServer).TestStreamFromClient(&backendTestStreamFromClientServer{stream})
}

type Backend_TestStreamFromClientServer interface {
	SendAndClose(*TestMessageResponse) error
	Recv() (*TestMessageRequest, error)
	grpc.ServerStream
}

type backendTestStreamFromClientServer struct {
	grpc.ServerStream
}

func (x *backendTestStreamFromClientServer) SendAndClose(m *TestMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backendTestStreamFromClientServer) Recv() (*TestMessageRequest, error) {
	m := new(TestMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Backend_TestStreamClientAndServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendServer).TestStreamClientAndServer(&backendTestStreamClientAndServerServer{stream})
}

type Backend_TestStreamClientAndServerServer interface {
	Send(*TestMessageResponse) error
	Recv() (*TestMessageRequest, error)
	grpc.ServerStream
}

type backendTestStreamClientAndServerServer struct {
	grpc.ServerStream
}

func (x *backendTestStreamClientAndServerServer) Send(m *TestMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backendTestStreamClientAndServerServer) Recv() (*TestMessageRequest, error) {
	m := new(TestMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mrga.backend.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUPV1",
			Handler:    _Backend_SignUPV1_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Backend_Login_Handler,
		},
		{
			MethodName: "CheckLogin",
			Handler:    _Backend_CheckLogin_Handler,
		},
		{
			MethodName: "BeginConversation",
			Handler:    _Backend_BeginConversation_Handler,
		},
		{
			MethodName: "GetConversations",
			Handler:    _Backend_GetConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _Backend_GetConversation_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Backend_SendMessage_Handler,
		},
		{
			MethodName: "GetDocumentCategories",
			Handler:    _Backend_GetDocumentCategories_Handler,
		},
		{
			MethodName: "SendRedirectSuggest",
			Handler:    _Backend_SendRedirectSuggest_Handler,
		},
		{
			MethodName: "GetHotThemes",
			Handler:    _Backend_GetHotThemes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestStreamFromServer",
			Handler:       _Backend_TestStreamFromServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TestStreamFromClient",
			Handler:       _Backend_TestStreamFromClient_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TestStreamClientAndServer",
			Handler:       _Backend_TestStreamClientAndServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ailawyer/backend.proto",
}
