apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speranskiy-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: khasbulat.ru
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speranskiy-backend-service
                port:
                  number: 7001
